version: '3.8'

services:
  node-app:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - elasticsearch
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 3000
      INDEX_URL: https://challenges.coode.sh/food/data/json/index.txt
      FILE_URL: https://challenges.coode.sh/food/data/json/
      MONGO_URL: mongodb://mongo:27017/foodData
      ELASTICSEARCH_URL: http://elasticsearch:9200
      SENTRY_DSN: https://d1a847e9dd10c1ee174ec641e0f78105@o4504663060578304.ingest.us.sentry.io/4507919120465920
      JWT_SECRET: 123456789
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
