version: '3.8'

services:
  node-app:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - elasticsearch
    volumes:
      - .:/usr/src/app
    environment:
      MONGO_URL: mongodb://mongo:27017/foodData
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
